# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.models.draw_rectangle_request import DrawRectangleRequest  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestDrawRectangleRequest(unittest.TestCase):
    """DrawRectangleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDrawRectangleRequest(self):
        """Test DrawRectangleRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_image_api_client.models.draw_rectangle_request.DrawRectangleRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
