# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.models.image_similarity_hash_distance_response import ImageSimilarityHashDistanceResponse  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestImageSimilarityHashDistanceResponse(unittest.TestCase):
    """ImageSimilarityHashDistanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageSimilarityHashDistanceResponse(self):
        """Test ImageSimilarityHashDistanceResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_image_api_client.models.image_similarity_hash_distance_response.ImageSimilarityHashDistanceResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
