# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.api.ai_image_detection_api import AiImageDetectionApi  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestAiImageDetectionApi(unittest.TestCase):
    """AiImageDetectionApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_image_api_client.api.ai_image_detection_api.AiImageDetectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ai_image_detection_detect_file(self):
        """Test case for ai_image_detection_detect_file

        Detect if an input image was generated using AI  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
