# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.api.text_generation_api import TextGenerationApi  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestTextGenerationApi(unittest.TestCase):
    """TextGenerationApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_image_api_client.api.text_generation_api.TextGenerationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_text_generation_create_handwriting_png(self):
        """Test case for text_generation_create_handwriting_png

        Create an image of handwriting in PNG format  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
