# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.api.artistic_api import ArtisticApi  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestArtisticApi(unittest.TestCase):
    """ArtisticApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_image_api_client.api.artistic_api.ArtisticApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_artistic_painting(self):
        """Test case for artistic_painting

        Transform an image into an artistic painting automatically  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
