# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.models.text_item import TextItem  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestTextItem(unittest.TestCase):
    """TextItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextItem(self):
        """Test TextItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_image_api_client.models.text_item.TextItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
