# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_image_api_client
from cloudmersive_image_api_client.api.edit_api import EditApi  # noqa: E501
from cloudmersive_image_api_client.rest import ApiException


class TestEditApi(unittest.TestCase):
    """EditApi unit test stubs"""

    def setUp(self):
        self.api = cloudmersive_image_api_client.api.edit_api.EditApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_composite_basic(self):
        """Test case for edit_composite_basic

        Composite two images together  # noqa: E501
        """
        pass

    def test_edit_draw_rectangle(self):
        """Test case for edit_draw_rectangle

        Draw rectangle onto an image  # noqa: E501
        """
        pass

    def test_edit_draw_text(self):
        """Test case for edit_draw_text

        Draw text onto an image  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
