# coding: utf-8

# flake8: noqa
"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from cloudmersive_image_api_client.models.age_detection_result import AgeDetectionResult
from cloudmersive_image_api_client.models.detected_license_plate import DetectedLicensePlate
from cloudmersive_image_api_client.models.detected_object import DetectedObject
from cloudmersive_image_api_client.models.draw_rectangle_instance import DrawRectangleInstance
from cloudmersive_image_api_client.models.draw_rectangle_request import DrawRectangleRequest
from cloudmersive_image_api_client.models.draw_text_instance import DrawTextInstance
from cloudmersive_image_api_client.models.draw_text_request import DrawTextRequest
from cloudmersive_image_api_client.models.face import Face
from cloudmersive_image_api_client.models.face_locate_response import FaceLocateResponse
from cloudmersive_image_api_client.models.image_description_response import ImageDescriptionResponse
from cloudmersive_image_api_client.models.nsfw_result import NsfwResult
from cloudmersive_image_api_client.models.object_detection_result import ObjectDetectionResult
from cloudmersive_image_api_client.models.person_with_age import PersonWithAge
from cloudmersive_image_api_client.models.recognition_outcome import RecognitionOutcome
from cloudmersive_image_api_client.models.vehicle_license_plate_detection_result import VehicleLicensePlateDetectionResult
