# coding: utf-8

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DrawTextInstance(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'font_family_name': 'str',
        'font_size': 'float',
        'color': 'str',
        'x': 'float',
        'y': 'float',
        'width': 'float',
        'height': 'float'
    }

    attribute_map = {
        'text': 'Text',
        'font_family_name': 'FontFamilyName',
        'font_size': 'FontSize',
        'color': 'Color',
        'x': 'X',
        'y': 'Y',
        'width': 'Width',
        'height': 'Height'
    }

    def __init__(self, text=None, font_family_name=None, font_size=None, color=None, x=None, y=None, width=None, height=None):  # noqa: E501
        """DrawTextInstance - a model defined in Swagger"""  # noqa: E501

        self._text = None
        self._font_family_name = None
        self._font_size = None
        self._color = None
        self._x = None
        self._y = None
        self._width = None
        self._height = None
        self.discriminator = None

        if text is not None:
            self.text = text
        if font_family_name is not None:
            self.font_family_name = font_family_name
        if font_size is not None:
            self.font_size = font_size
        if color is not None:
            self.color = color
        if x is not None:
            self.x = x
        if y is not None:
            self.y = y
        if width is not None:
            self.width = width
        if height is not None:
            self.height = height

    @property
    def text(self):
        """Gets the text of this DrawTextInstance.  # noqa: E501

        Text string to draw  # noqa: E501

        :return: The text of this DrawTextInstance.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this DrawTextInstance.

        Text string to draw  # noqa: E501

        :param text: The text of this DrawTextInstance.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def font_family_name(self):
        """Gets the font_family_name of this DrawTextInstance.  # noqa: E501

        Font Family to use.  Leave blank to default to \"Arial\".  # noqa: E501

        :return: The font_family_name of this DrawTextInstance.  # noqa: E501
        :rtype: str
        """
        return self._font_family_name

    @font_family_name.setter
    def font_family_name(self, font_family_name):
        """Sets the font_family_name of this DrawTextInstance.

        Font Family to use.  Leave blank to default to \"Arial\".  # noqa: E501

        :param font_family_name: The font_family_name of this DrawTextInstance.  # noqa: E501
        :type: str
        """

        self._font_family_name = font_family_name

    @property
    def font_size(self):
        """Gets the font_size of this DrawTextInstance.  # noqa: E501

        Font size to use.  # noqa: E501

        :return: The font_size of this DrawTextInstance.  # noqa: E501
        :rtype: float
        """
        return self._font_size

    @font_size.setter
    def font_size(self, font_size):
        """Sets the font_size of this DrawTextInstance.

        Font size to use.  # noqa: E501

        :param font_size: The font_size of this DrawTextInstance.  # noqa: E501
        :type: float
        """

        self._font_size = font_size

    @property
    def color(self):
        """Gets the color of this DrawTextInstance.  # noqa: E501

        Color to use - can be a hex value (with #) or HTML common color name  # noqa: E501

        :return: The color of this DrawTextInstance.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this DrawTextInstance.

        Color to use - can be a hex value (with #) or HTML common color name  # noqa: E501

        :param color: The color of this DrawTextInstance.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def x(self):
        """Gets the x of this DrawTextInstance.  # noqa: E501

        Pixel location of the left edge of the text location  # noqa: E501

        :return: The x of this DrawTextInstance.  # noqa: E501
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this DrawTextInstance.

        Pixel location of the left edge of the text location  # noqa: E501

        :param x: The x of this DrawTextInstance.  # noqa: E501
        :type: float
        """

        self._x = x

    @property
    def y(self):
        """Gets the y of this DrawTextInstance.  # noqa: E501

        Pixel location of the top edge of the text location  # noqa: E501

        :return: The y of this DrawTextInstance.  # noqa: E501
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this DrawTextInstance.

        Pixel location of the top edge of the text location  # noqa: E501

        :param y: The y of this DrawTextInstance.  # noqa: E501
        :type: float
        """

        self._y = y

    @property
    def width(self):
        """Gets the width of this DrawTextInstance.  # noqa: E501

        Width in pixels of the text box to draw the text in; text will wrap inside this box  # noqa: E501

        :return: The width of this DrawTextInstance.  # noqa: E501
        :rtype: float
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this DrawTextInstance.

        Width in pixels of the text box to draw the text in; text will wrap inside this box  # noqa: E501

        :param width: The width of this DrawTextInstance.  # noqa: E501
        :type: float
        """

        self._width = width

    @property
    def height(self):
        """Gets the height of this DrawTextInstance.  # noqa: E501

        Height in pixels of the text box to draw the text in; text will wrap inside this box  # noqa: E501

        :return: The height of this DrawTextInstance.  # noqa: E501
        :rtype: float
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this DrawTextInstance.

        Height in pixels of the text box to draw the text in; text will wrap inside this box  # noqa: E501

        :param height: The height of this DrawTextInstance.  # noqa: E501
        :type: float
        """

        self._height = height

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DrawTextInstance, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DrawTextInstance):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
