# coding: utf-8

# flake8: noqa

"""
    imageapi

    Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from cloudmersive_image_api_client.api.face_api import FaceApi
from cloudmersive_image_api_client.api.nsfw_api import NsfwApi
from cloudmersive_image_api_client.api.recognize_api import RecognizeApi
from cloudmersive_image_api_client.api.resize_api import ResizeApi

# import ApiClient
from cloudmersive_image_api_client.api_client import ApiClient
from cloudmersive_image_api_client.configuration import Configuration
# import models into sdk package
from cloudmersive_image_api_client.models.face import Face
from cloudmersive_image_api_client.models.face_locate_response import FaceLocateResponse
from cloudmersive_image_api_client.models.image_description_response import ImageDescriptionResponse
from cloudmersive_image_api_client.models.nsfw_result import NsfwResult
from cloudmersive_image_api_client.models.recognition_outcome import RecognitionOutcome
